# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: demo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ndemo.proto\x12\x04\x64\x65mo\"\xbb\x04\n\x07Request\x12\x11\n\tclient_id\x18\x01 \x01(\x03\x12\x14\n\x0crequest_data\x18\x02 \x01(\t\x12$\n\x1clegacy_gw_received_frame_num\x18\x03 \x01(\x03\x12+\n#legacy_gw_received_frame_unique_num\x18\x04 \x01(\x03\x12\'\n\x1flegacy_gw_transmitted_frame_num\x18\x05 \x01(\x03\x12!\n\x19\x45\x32L_gw_received_frame_num\x18\x06 \x01(\x03\x12(\n E2L_gw_received_frame_unique_num\x18\x07 \x01(\x03\x12$\n\x1c\x45\x32L_gw_transmitted_frame_num\x18\x08 \x01(\x03\x12)\n!module_received_frame_from_ns_num\x18\t \x01(\x03\x12)\n!module_received_frame_from_gw_num\x18\n \x01(\x03\x12)\n!devices_key_agreement_message_log\x18\x0b \x01(\t\x12$\n\x1cgw_key_agreement_message_log\x18\x0c \x01(\t\x12(\n module_key_agreement_message_log\x18\r \x01(\t\x12\"\n\x1akey_agreement_process_time\x18\x0e \x01(\x03\x12#\n\x1b\x61ggregation_function_result\x18\x0f \x01(\x03\"\x99\x01\n\x08Response\x12\x11\n\tserver_id\x18\x01 \x01(\x03\x12\x15\n\rresponse_data\x18\x02 \x01(\t\x12\x19\n\x11legacy_device_num\x18\x03 \x01(\x03\x12\x16\n\x0e\x45\x32L_device_num\x18\x04 \x01(\x03\x12\x18\n\x10process_function\x18\x05 \x01(\t\x12\x16\n\x0eprocess_window\x18\x06 \x01(\x03\x32\xf0\x01\n\x08GRPCDemo\x12-\n\x0cSimpleMethod\x12\r.demo.Request\x1a\x0e.demo.Response\x12\x38\n\x15\x43lientStreamingMethod\x12\r.demo.Request\x1a\x0e.demo.Response(\x01\x12\x38\n\x15ServerStreamingMethod\x12\r.demo.Request\x1a\x0e.demo.Response0\x01\x12\x41\n\x1c\x42idirectionalStreamingMethod\x12\r.demo.Request\x1a\x0e.demo.Response(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'demo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_REQUEST']._serialized_start=21
  _globals['_REQUEST']._serialized_end=592
  _globals['_RESPONSE']._serialized_start=595
  _globals['_RESPONSE']._serialized_end=748
  _globals['_GRPCDEMO']._serialized_start=751
  _globals['_GRPCDEMO']._serialized_end=991
# @@protoc_insertion_point(module_scope)
